task:
  matrix:
    - name: FreeBSD
      freebsd_instance:
        image: freebsd-12-0-release-amd64
    - name: Linux
      container:
        image: fedora:latest
  artifacts_cache:
    folder: ~/.julia/artifacts
  env:
    JULIA_VERSION: 1.0
    JULIA_VERSION: 1.8
    JULIA_VERSION: nightly
  allow_failures: $JULIA_VERSION == 'nightly'
  install_script: |
    URL="https://raw.githubusercontent.com/ararslan/CirrusCI.jl/master/bin/install.sh"
    if command -v curl; then
        sh -c "$(curl ${URL})"
    elif command -v wget; then
        sh -c "$(wget ${URL} -q -O-)"
    elif command -v fetch; then
        sh -c "$(fetch ${URL} -o -)"
    fi
  build_script:
    - cirrusjl build
  test_script:
    - cirrusjl test
  coverage_script:
    - cirrusjl coverage codecov coveralls
